# Generated by Django 5.1.4 on 2024-12-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('의원코드', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('이름', models.CharField(blank=True, max_length=100, null=True)),
                ('한자이름', models.CharField(blank=True, max_length=100, null=True)),
                ('영문이름', models.CharField(blank=True, max_length=200, null=True)),
                ('생년월일', models.CharField(blank=True, max_length=20, null=True)),
                ('직책', models.CharField(blank=True, max_length=200, null=True)),
                ('정당', models.CharField(blank=True, max_length=100, null=True)),
                ('선거구', models.CharField(blank=True, max_length=200, null=True)),
                ('선거구구분', models.CharField(blank=True, max_length=100, null=True)),
                ('위원회', models.CharField(blank=True, max_length=500, null=True)),
                ('소속위원회', models.CharField(blank=True, max_length=500, null=True)),
                ('당선횟수', models.CharField(blank=True, max_length=100, null=True)),
                ('당선대수', models.CharField(blank=True, max_length=100, null=True)),
                ('성별', models.CharField(blank=True, max_length=10, null=True)),
                ('전화번호', models.CharField(blank=True, max_length=100, null=True)),
                ('이메일', models.CharField(blank=True, max_length=200, null=True)),
                ('홈페이지', models.URLField(blank=True, max_length=500, null=True)),
                ('보좌관', models.CharField(blank=True, max_length=200, null=True)),
                ('비서관', models.CharField(blank=True, max_length=200, null=True)),
                ('비서', models.CharField(blank=True, max_length=200, null=True)),
                ('약력', models.TextField(blank=True, null=True)),
                ('사무실호실', models.CharField(blank=True, max_length=100, null=True)),
                ('사진', models.URLField(blank=True, max_length=500, null=True)),
                ('생성일시', models.DateTimeField(auto_now_add=True)),
                ('수정일시', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('회의록ID', models.CharField(max_length=100, unique=True)),
                ('대수', models.CharField(max_length=10)),
                ('회기', models.CharField(max_length=10)),
                ('차수', models.CharField(max_length=10)),
                ('회의일자', models.DateField()),
                ('회의종류', models.CharField(max_length=100)),
                ('위원회코드', models.CharField(max_length=20)),
                ('위원회명', models.CharField(max_length=100)),
                ('회의록URL', models.URLField()),
            ],
            options={
                'ordering': ['-회의일자'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archive.conference')),
            ],
        ),
    ]
